# This is a basic workflow to help you get started with Actions
name: CI for Demo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  name: 'Prateek'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-context-info:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      task: 'workflow job'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:  
      - name: env context
        run: echo Hello $name, running $task for ${{ env.step }} script
        env:
          step: 'one line'
          
      - name: github context
        run: |
          echo Run a multi-line script
          echo Owner: ${{ github.repository_owner }}
          echo Repository: ${{ github.repository }}
          echo Branch: ${{ github.ref_name }}
          
      - name: vars context
        run: |
            echo API_URL: ${{ vars.API_URL }}
            echo CLIENT_ID: ${{ vars.CLIENT_ID }}
            
      - name: secrets context
        run: |
            echo API_KEY: ${{ secrets.API_KEY }}
            API_KEY
            echo API_SECRET: ${{ secrets.API_SECRET }}
            API_SECRET
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4
      #- name: List of checkout files
      #  run: |
      #    pwd
      #    ls -ll
